model:
  base_learning_rate: 1.0e-6
  max_steps: 60000
  scheduler_params:
    type: OneCycle
    max_lr: 1.0e-4
    total_steps: 60000
    pct_start: 0.02
  target: taming.models.crosslformer.CrossLformerLatent
  params:
    css: 32
    w_layer: 12
    transformer_config:
      target: taming.modules.transformer.sandwich.GPT
      params:
        dim_cond: 512 # num of dimensions of condition hidden
        block_size: 1024
        text_vbs: 0
        img_vbs: 1024
        n_layer: 19
        n_head: 16
        n_embd: 1024
        embd_pdrop: 0.1
        resid_pdrop: 0.1
        attn_pdrop: 0.1
        add_cross: True
        full_head: False
        PBrelax: False
        checkpoint: 16
    text_encoder_config:
      target: taming.models.custom_clip.TextEncoder
      params: 
        ckpt_path: /home/ma-user/work/lijiacheng/pretrained/ViT-B-16.pt
        freeze: True
        
    # taming VQGAN CelebA
    first_stage_config:
      target: taming.models.vqgan.VQModel
      params:
        ckpt_path: /home/ma-user/work/lijiacheng/vqmodel/faces/celeba_f8.ckpt
        embed_dim: 256
        n_embed: 1024
        ddconfig:
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [1,1,2,4]
          num_res_blocks: 2
          attn_resolutions: [32]
          dropout: 0.0
        lossconfig:
          target: third_party.losses.vqperceptual.DummyLoss

data: #CelebA
  target: taming.data.utils.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 8
    train:
      target: taming.data.celeba.CelebAFeature
      params:
        split: train
        img_size: 288
        crop_size: 256
        img_root: /cache/CelebAMask-HQ/CelebA-HQ-img
        meta: /cache/CelebAMask-HQ/metadata.pkl
        fea: /cache/CelebAMask-HQ/feature_celeba_clip_train.pkl
    validation:
      target: taming.data.celeba.CelebAFeature
      params:
        split: test
        img_size: 288
        crop_size: 256
        img_root: /cache/CelebAMask-HQ/CelebA-HQ-img
        meta: /cache/CelebAMask-HQ/metadata.pkl
        fea: /cache/CelebAMask-HQ/feature_celeba_clip_val.pkl
