data: #COCO
  target: taming.data.utils.DataModuleFromConfig
  params:
    batch_size: 32
    num_workers: 16
    train:
      target: taming.data.coco.COCO
      params:
        split: train
        img_size: 256
        crop_size: 224
        mean: [0.48145466, 0.4578275, 0.40821073]
        std: [0.26862954, 0.26130258, 0.27577711]
        img_root: /cache/coco/train2017
        meta: /home/ma-user/work/lijiacheng/data/coco/metadata_coco_train.pkl
    validation:
      target: taming.data.coco.COCO
      params:
        split: test
        img_size: 256
        crop_size: 224
        mean: [0.48145466, 0.4578275, 0.40821073]
        std: [0.26862954, 0.26130258, 0.27577711]
        img_root: /cache/coco/val2017
        meta: /home/ma-user/work/lijiacheng/data/coco/metadata_coco_val.pkl

clip_ckpt_path: /home/ma-user/work/lijiacheng/pretrained/ViT-B-16.pt
save_prefix: /data/s3/features/feature_coco_clip # will add .pkl automaticallly
