data: #CelebA
  target: taming.data.utils.DataModuleFromConfig
  params:
    batch_size: 32
    num_workers: 8
    train:
      target: taming.data.celeba.CelebA
      params:
        split: train
        img_size: 256
        crop_size: 224
        mean: [0.48145466, 0.4578275, 0.40821073]
        std: [0.26862954, 0.26130258, 0.27577711]
        img_root: /cache/CelebAMask-HQ/CelebA-HQ-img
        meta: /cache/CelebAMask-HQ/metadata.pkl
    validation:
      target: taming.data.celeba.CelebA
      params:
        split: test
        img_size: 256
        crop_size: 224
        mean: [0.48145466, 0.4578275, 0.40821073]
        std: [0.26862954, 0.26130258, 0.27577711]
        img_root: /cache/CelebAMask-HQ/CelebA-HQ-img
        meta: /cache/CelebAMask-HQ/metadata.pkl

clip_ckpt_path: /home/ma-user/work/lijiacheng/pretrained/ViT-B-16.pt
save_prefix: /data/s3/features/feature_celeba_clip